### ISSUE TITLE
!!! CHECKLIST A SER FEITO AOS SÁBADOS  !!!

### ISSUE THREAD

**Issue by dougs007** [cpa-bayarea/Prontuario-eletronico#17]
Segue lista de checklist a serem feitas todos os sábados pela equipe.

#### ``Checklist da Equipe``
- [ ] Contar com a participação de todos os membros (2).
- [ ] Verificar se estão com Dúvidas e se estão executando as demandas com Êxito.
- [ ] Solicitar ajuda aos demais membros caso necessite para execução de demanda.
- [ ] Seguir as Regras estipuladas do Projeto. ( Presença e Proatividade )

#### ``Checklist do Gerente``

- [ ] Verificar com o CEP ( Centro de Pesquisas Psicológicas ) se os dados dos formulários estão de acordo com o cotidiano deles.
- [ ] Manter-se alinhado com o CEP sobre o sistema e verificar as funcionalidades, melhorias e feedback sobre o sistema.
- [ ] Verificar se estão com Dúvidas e se estão executando as demandas com Êxito.
- [ ] Verificar se estão concluindo as demandas no prazo estipulado.
- [ ] Verificar se o tempo executado foi menor ao tempo estimulado ou igual das demandas estipuladas.
- [ ] Produzir Relatório do que foi feito durante a Sprint.
